VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('24')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('19')
MAJOR_VERSION = 0
MINOR_VERSION = 1
PATCH_VERSION = 202401241019
version_date = '2024/01/24 10:19'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
