VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('22')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('57')
MAJOR_VERSION = 0
MINOR_VERSION = 0
PATCH_VERSION = 202401220957
version_date = '2024/01/22 09:57'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
